### ISSUE TITLE
pls check this survey

### ISSUE THREAD

**Issue by XiaoxinHe** [ChandlerBang/awesome-graph-transformer#1]
Transformer for Graphs: An Overview from Architecture Perspective. Arxiv 2022. [[paper]](https://arxiv.org/abs/2202.08455)

**Comment by wehos** [comment]
Hi! Thank you for reminding! I have merged all papers from the survey you mentioned, most of which are classified into "**Applications of Graph Transformers**" category in this repo. The survey paper itself is put in the new 'Survey' category.
