### ISSUE TITLE
Could you please add TGT to your list

### ISSUE THREAD

**Issue by shamim-hussain** [ChandlerBang/awesome-graph-transformer#10]
Hi,

I am the author of "Global Self-Attention as a Replacement for Graph Convolution", aka, the EGT paper. Thank you for making this awesome list - very useful and insightful.

Recently we improved upon our previous work by incorporating triplet (third-order) interactions. Along with an improved training and inference framework, this allows us to achieve SOTA results on multiple molecular graph benchmarks, including PCQM4Mv2 and OC20. Triplet interaction is shown to be useful for other tasks involving geometry (e.g., TSP) as well. We call the new framework Triplet Graph Transformer.

Paper link: [https://arxiv.org/abs/2402.04538](https://arxiv.org/abs/2402.04538)
Code: [https://github.com/shamim-hussain/tgt](https://github.com/shamim-hussain/tgt)

Could you please add this to your list? Or maybe I can open a pull request?

Regards,
Md Shamim Hussain

**Comment by wehos** [comment]
Hi Shamim,

I just read the paper, very awesome work! I'm thrilled to add it to the repo. The [commit](https://github.com/wehos/awesome-graph-transformer/commit/d735e2209c4f0b472e925b1f593dd01388708b78) has been merged.

Best,
Hongzhi

**Comment by shamim-hussain** [comment]
Thank You!
