### ISSUE TITLE
NodeFormer from NeurIPS22

### ISSUE THREAD

**Issue by qitianwu** [ChandlerBang/awesome-graph-transformer#2]
Dear authors,

Thanks for your making this great survey. Here is a NeurIPS22 spotlight paper "NodeFormer: A Scalable Graph Structure Learning Transformer for Node Classification", about graph Transformer for node classification, latent structure learning and addressing the scalability issue with kernelized approximation.

**Comment by wehos** [comment]
Thanks for bringing up this work! It is highly interesting and insightful. We are more than happy to add it to our paper list!
